language: php

php:
  - 7.1

addons:
  - firefox: "52.0.1"
  - chrome: ""

install:
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - cp .env.travis .env
  - php artisan key:generate
  - echo "" > ./database/testing.sqlite

script:
  - vendor/bin/phpunit
  - php artisan dusk