sudo: required
language: php

php:
  - 7.1

before_script:
  - sudo apt-get install -y nodejs
  - node -v
  - npm -v
  - sudo npm update npm -g
  - node -v
  - npm -v
  - sudo npm install n -g
  - sudo n latest
  - node -v
  - npm -v
  - sudo npm update npm -g
  - node -v
  - npm -v
  - npm install
  - npm run production
  - composer self-update
  - composer install --dev --no-interaction --prefer-source
  - cp ./.env.travis ./.env
  - touch ./database/testing.sqlite

script: vendor/bin/phpunit