sudo: required
language: php

php:
  - 7.1

cache:
  directories:
    - "travis_phantomjs"

before_install:
  - export TRAVIS_PHANTOMJS_INSTALL_PATH="$PWD/travis_phantomjs"
  - export TRAVIS_PHANTOMJS_VERSION_NAME="phantomjs-2.1.1-linux-x86_64"
  - export PATH="$TRAVIS_PHANTOMJS_INSTALL_PATH/$TRAVIS_PHANTOMJS_VERSION_NAME/bin:$PATH"
  - hash -d phantomjs || true
  - echo "phantomjs version is $(phantomjs --version)"
  - if [ $(phantomjs --version) != '2.1.1' ]; then $PWD/bin/travis_get_updated_phantomjs; hash -d phantomjs || true; echo "updated phantomjs version is $(phantomjs --version)"; fi

install:
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - cp .env.travis .env
  - php artisan key:generate
  - echo "" > ./database/testing.sqlite

before_script:
  - phantomjs --webdriver=127.0.0.1:9515 --web-security=no --ignore-ssl-errors=yes &
  - php artisan serve &
  - sleep 5

script:
  - vendor/bin/phpunit
  - php artisan dusk