sudo: required
language: php

php:
  - 7.1

branches:
  only:
    - master

before_script:
  - composer self-update
  - composer install --dev --no-interaction --prefer-source

script: vendor/bin/phpunit