sudo: required
language: php node_js

php:
  - 7.1

node_js:
  - 6

before_script:
  - php -v
  - node -v
  - npm -v
  - composer self-update
  - composer install --dev --no-interaction --prefer-source
  - cp ./.env.travis ./.env
  - touch ./database/testing.sqlite
  - npm install
  - npm run production

script: vendor/bin/phpunit