language: php

php:
  - 7.1

install:
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - cp .env.travis .env
  - php artisan key:generate
  - echo "" > ./database/testing.sqlite

before_script:
  - phantomjs --webdriver=127.0.0.1:9515 &
  - php artisan serve &
  - sleep 5

script:
  - vendor/bin/phpunit
  - php artisan dusk