sudo: required
language: php

php:
  - 7.1

before_script:
  - composer self-update
  - composer install --dev --no-interaction --prefer-source
  - cp ./.env.travis ./.env
  - php artisan key:generate

script:
  - vendor/bin/phpunit
  - php artisan dusk